<?php

namespace AppBundle\Repository;

/**
 * LiftAvailableFloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiftAvailableFloorRepository extends \Doctrine\ORM\EntityRepository
{
}
