<?php

namespace AppBundle\Repository;

/**
 * LiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiftRepository extends \Doctrine\ORM\EntityRepository
{
}
